"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['calculator.py']
DATA_FILES = ['--add-data',
 'Assets/Dependencies',
 'Assets/GTXR RING LOGO.png',
 'Assets/RRC RING LOGO.png',
 'Assets/Rocket tracker Icon.ai',
 'Assets/Rocket tracker Icon.png',
 'Assets/wileyind.png']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],

)
